Homework1
agate-agate/learnpython_homeworks pull request #1
Opened 2020-09-12 09:27 UTC by agate-agate

2020-09-12 09:58 UTC, dolfinus requested changes
В целом очень хорошо.

Из критичного только использование `_` в качестве названия переменной.

2020-09-12 09:58 UTC, dolfinus commented on homework1/1_if1.py
> +        age = float(str(age))
Необычно, что возраст является числом с дробной частью. Это на вряд ли пользователь додумается такое ввести :)

2020-09-12 09:58 UTC, dolfinus commented on homework1/1_if1.py
> +    if (age >= 0 + 7 + 11 + 5):
Это весьма сложно читается. Лучше не суммировать кучу непонятных чисел, а определит константы, так будет понятнее.

2020-09-12 09:58 UTC, dolfinus commented on homework1/1_if1.py
> +    if (age >= 0 + 7 + 11 + 5):
И еще, в python скобочки в сравнениях совершенно не обязательны. Большинство code styles требуют, чтобы их не было, потому что о них только будешь спотыкаться, когда читаешь код.

2020-09-12 09:58 UTC, dolfinus commented on homework1/3_for.py
> +        for score in record['scores']:
Можно не проходить по каждому значению, суммируя/инкрементируя переменные вручную, а воспользоваться функциями `sum` и `len`

2020-09-12 09:58 UTC, dolfinus commented on homework1/3_for.py
> +        print(
Рекомендую вместо сложения строк воспользоваться методом `format`:
`"This is {val}".format(val='awesome')`
Тогда и значения не придется приводить к строке.

2020-09-12 09:58 UTC, dolfinus commented on homework1/4_while1.py
> +            is_further_trolling_necessary = False
Можно использовать `break` вместо переменной, раз она больше ничего не делает.

2020-09-12 09:58 UTC, dolfinus commented on homework1/5_while2.py
> +        query = (str(input('Задайте вопрос: '))).strip()
`input` всегда возвращает строку, приведение к `str` совершенно не нужно.
А вот за `strip` зачет, весьма полезно очищать ввод.

2020-09-12 09:58 UTC, dolfinus commented on homework1/5_while2.py
> +        if query.lower() == 'отпусти меня!!!':
Можно сразу привести ввод к lowercase, чтобы не делать это в нескольких местах.

2020-09-12 09:58 UTC, dolfinus commented on homework1/5_while2.py
> +        if query.lower() == 'ааа!!!':
Я бы рекомендовал завести отдельный dict с вариантами ввода, которые приведут к прерыванию выполнения команды, вместо нескольких if внутри функции.

Например:
```python
if query in exit_values:
  print(exit_values[query])
  break
```

Но так тоже можно.

2020-09-12 09:58 UTC, dolfinus commented on homework1/7_exception2.py
> +    def to_int(num):
Можно так. А можно и перехватывать исключение в самой функции get_summ, и в случае ошибки выводить на экран осмысленный текст.
Сейчас получается, что у `"six" + "шесть" == 0`, что немного странно.

2020-09-12 09:58 UTC, dolfinus commented on homework1/8_ephem_bot.py
> +        _ = str(text_pieces[1])
Ой, не надо так. Подчеркивание используется для того, чтобы выбросить какую-то часть разобранной строки, например:
```python
inp = "something=1"
_, value = imp.split('=')
```
Значение `"something"` будет присвоено переменной `_`, но оно никогда больше не будет использоваться. На это в том числе заточены инструменты для статического анализа кода.
```

2020-09-12 09:58 UTC, dolfinus commented on homework1/8_ephem_bot.py
> +    message_lines = [
В python есть многострочные строки:
```python
"""
Это
строка
из
нескольких
строк
"""
```
По возможности стоит использовать их вместо списка строк + конкатенации.

2020-09-12 09:58 UTC, dolfinus commented on homework1/easy_planets.py
> +    _ = (str(raw_planet_name)).strip().lower()
Аналогично замечанию выше про использование переменной с названием `_`.

2020-09-12 09:58 UTC, dolfinus commented on homework1/easy_planets.py
> +    ephem_planet = get_ephem_planet(raw_planet_name)
Этот код полностью ок, но есть одна рекомендация на будущее.
Если у тебя есть отдельный метод для возврата планеты по ее имени, лучше вместо его вызова в начале функции ожидать на вход сразу планету.

Это в будущем упростит:
1. Расширение функционала
2. Написание тестов

В некоторых случаях этот подход не используют, например когда пишут библиотеки, функции в которых должны обрабатывать пользовательский ввод. Но это обычно исключение.

2020-09-12 09:58 UTC, dolfinus commented on homework1/easy_planets.py
> +    except AttributeError:
Можно так, а можно воспользоваться функцией `hasattr`, и если метода нет, сразу возвращать `None`, без выброса исключения. Обычно исключения стараются использовать в крайних случаях, они немного засоряют код и работают медленнее сравнений.

2020-09-12 11:13 UTC, dolfinus commented on homework1/easy_planets.py
> +# easy_planets.py:64: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
Warning это не исключение, это предупреждение. Обычно связанное с тем, что что-то устарело.

Например, когда библиотека написана под python2, а ты запускаешь ее под python3, где принято делать некоторые вещи немного иначе.

Или когда ты используешь какую-то сторонюю библиотеку, у которой от версии к версии меняется логика работы функций.
Скажем, в библиотеке с самой ее первой версии (1.0.0) есть функция `get_something(arg1)`. В версии 1.0.1 в нее добавляют дополнительный аргумент `get_something(arg1, arg2=None)`. У него есть значение по-умолчанию, поэтому код, написанный для предыдущей версии библиотеки, вполне работает и с новой, потому что аргумент необязательный. Но при вызове этой функции выводится предупреждение, что скоро он станет обязательным.

Ты работаешь с новой версией, видишь предупреждение, переходить на сайт проекта/репозиторий, видишь рекомендацию добавить второй аргумент при вызове функций, и добавляешь его.
А потом выходит версия `1.1.0`, где у аргумента убирают значение по-умолчанию, и код, в котором ты вызывал функцию с одним аргументом, больше работать не будет. Но ты внимательный, и уже переписал его, поэтому ошибки не возникнет.

А вот если бы не было этого warning, ты бы спокойно обновил версию либы ("ой, да кто читает, что там изменилось в 1.1") и все бы пошло наперекосяк. Это не самый лучший подход :)

2020-09-12 11:25 UTC, agate-agate commented on homework1/1_if1.py
> +        age = float(str(age))
Я бы оставил float чтобы сохранить шутку про от -9 месяцев до 0 месяцев))) Юмор иногда полезен даже если не все его найдут)))

И общий функционал от этой мелочи не пострадает, поэтому я думаю что можно оставить как есть)))

2020-09-12 11:41 UTC, agate-agate commented on homework1/1_if1.py
> +    if (age >= 0 + 7 + 11 + 5):
done...

2020-09-12 11:41 UTC, agate-agate commented on homework1/1_if1.py
> +    if (age >= 0 + 7 + 11 + 5):
done...

2020-09-12 11:49 UTC, agate-agate commented on homework1/8_ephem_bot.py
> +        _ = str(text_pieces[1])
done...

2020-09-12 11:49 UTC, agate-agate commented on homework1/easy_planets.py
> +    _ = (str(raw_planet_name)).strip().lower()
done...

2020-09-12 12:16 UTC, agate-agate commented on homework1/3_for.py
> +        print(
done...

2020-09-12 12:26 UTC, agate-agate commented on homework1/8_ephem_bot.py
> +    message_lines = [
Ок. но в данном случае я просто оставил себе задел на будущее:
    message_lines = [
        'Вызван /planet',
        f'Ты хочешь узнать про планету: {raw_planet_name}',
        f'Которая распозналась как: {planet_name}',
        f'Она находится в созвездии: {constellation_label}',
    ]
Я когда писал это я типа не уверен был как более интуитивно будет для пользователей - всегда показывать все эти 4 строчки всегда или же сделать такое поведение:
1. если planet_name == '' то не показывать строчку f'Которая распозналась как: {planet_name}',
2. если constellation_label == '' то не показывать строчку f'Которая распозналась как: {constellation_label}',

С моей точки зрения текущий вариант подходящий, но я не всегда угадываю с тем как мыслят живые люди или Заказчик, поэтому это та вещь которую надо проверять на кошках. а если есть 50% шанс что это будет переделываться - пусть лучше остаётся в гибком виде. По-моему читаемость в целом неплохая - не находите?

2020-09-12 18:33 UTC, agate-agate commented on homework1/3_for.py
> +        for score in record['scores']:
done...

2020-09-12 19:24 UTC, agate-agate commented on homework1/easy_planets.py
> +# easy_planets.py:64: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
Понятно. Я поискал на сайте разработчика упоминания строки PY_SSIZE_T_CLEAN с помощью google.com site:
Ноль совпадений. Когда посмотрел документацию по https://rhodesmill.org/pyephem/tutorial.html#computing-with-dates
тоже ноль вещей за которые можно зацепиться чтобы убрать варнинг.

Пытался посмотреть исходный код проекта pyephem https://github.com/brandon-rhodes/pyephem - и мне кажется судя по тексту ошибки что проблема тут:

https://github.com/brandon-rhodes/pyephem/blob/1bb605c6c6fd99b55521953e02229e3fa43baa88/extensions/_libastro.c#L2814

но это язык программирования C - а не специалист по C
не знаю. У меня стаковерфлоу начинается когда я пытаюсь понять как этот проект вообще собирается из разных кусков. Я не настолько волшебник и даже не понятно за какой конец хвататься чтобы распутать этот клубок.

2020-09-12 19:45 UTC, agate-agate commented on homework1/easy_planets.py
> +    except AttributeError:
done...

2020-09-13 13:28 UTC, agate-agate commented on homework1/easy_planets.py
> +    ephem_planet = get_ephem_planet(raw_planet_name)
done...

2020-09-14 09:35 UTC, dolfinus commented on homework1/4_while1.py
> +    is_further_trolling_necessary = True
Переменная больше нигде не используется, стоит убрать.

2020-09-14 09:36 UTC, dolfinus commented on homework1/3_for.py
> +    if not isinstance(list_of_scores, list):
Никто, кроме тебя, эту функцию не будет использовать. Зачем тут проверка типа?

2020-09-14 09:37 UTC, dolfinus commented on homework1/5_while2.py
> +        answer = str(conversation_responses.get(query, ''))
Приведение к строке не обязательно.

2020-09-14 10:35 UTC, dolfinus commented on homework1/8_ephem_bot.py
> +    message_lines = [
Ммм, но ведь без названия планеты будет пустой результат. Тогда будет выводиться "Ты хочешь узнать про планету: \nКоторая распозналась как: \nОна находится в созвездии: ". Не самый полезный вывод. Рекомендую выводить здесь ошибку ("Не удалось распознать название планеты!").

Задел на будущее - это неплохо, когда дело касается архитектуры (модульность, возможность запуска нескольких копий приложения для того, чтобы оно могло обрабатывать больше запросов в секунду и т.п.). Но когда это предусмотрительность ради предусмотрительности, код в конечном итоге становится мертвым.
Ты будешь тратить время на его поддержку (исправление багов, поддержание в рабочем состоянии при обновлении зависимостей или питона), но им никто не будет пользоваться. Так зачем тратить на него время?

При разработке новых продуктов используется такое понятие как MVP (minimal valuable product) - ты разрабатываешь минимально работоспособное приложение, проводишь демонстрацию руководству/заказчику и собираешь отзывы. Когда появляются фичи, которые нужны кому-либо, реализуешь их. Мертвого кода в таком случае получается совсем немного + ты не тратишь время на угадывание, пойдет так или нет.

Читаемость - может быть, но при разработке важно все в комплексе.

2020-09-14 10:39 UTC, dolfinus commented on homework1/easy_planets.py
> +# easy_planets.py:64: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
Рекомендую просто не обращать на это внимание. Это одноразовое ДЗ, которое больше нигде не будет использоваться, ради него лезть в дебри компиляции модуля на C гиблое дело.

2020-09-14 10:42 UTC, dolfinus approved these changes

2020-09-14 19:49 UTC, merged

2020-09-16 04:10 UTC, agate-agate commented on homework1/8_ephem_bot.py
> +    message_lines = [
Хм, запомню, интересно.